# schema: https://scanner.dev/schema/scanner-detection-rule.v1.json
name: 1Password User MFA Settings Changed
description: |-
  Detect when a user creates, updates, or disables user account MFA settings
  in 1Password.
enabled: true
severity: Medium
query_text: |-
  %ingest.source_type:1password
  action:(enblmfa updatmfa disblmfa)
  object_type:user
  | groupbycount(actor_details.email)
  | where @q.count > 0
time_range_s: 300
run_frequency_s: 60
event_sink_keys:
- medium_severity_alerts
tags:
- tactics.ta0003.persistence
- tactics.ta0005.defense_evasion
- techniques.t1556.modify_authentication_process
- source.1password
